### ISSUE TITLE
Ruby 2.3.x?

### ISSUE THREAD

**Issue by axlekb** [whoward/jslint-v8#9]
Hi William,
  Thanks for providing this.  Have you had any luck running this on Ruby 2.3.x?

Seemed to work on older versions, but get this error with `2.3.0`.  Haven't looked into it much, but figured I'd ask first!

```
/Users/alexbowman/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x3fd4da0a8090 jslint-v8-1.1.3> (NoMethodError)
    from /Users/alexbowman/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
    from /Users/alexbowman/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
    from /Users/alexbowman/.rvm/gems/ruby-2.3.0/gems/jslint-v8-1.1.3/bin/jslint-v8:4:in `<top (required)>'
    from /Users/alexbowman/.rvm/gems/ruby-2.3.0/bin/jslint-v8:23:in `load'
    from /Users/alexbowman/.rvm/gems/ruby-2.3.0/bin/jslint-v8:23:in `<main>'
    from /Users/alexbowman/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
    from /Users/alexbowman/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by whoward** [comment]
I've actually seen this error from other gems - If I recall correctly it is actually an error with rubygems itself and not any particular gem, try upgrading your local rubygems and see if that fixes it.

**Comment by axlekb** [comment]
Wow. Great! That did it.  Thanks so much for saving me a giant waste of time!
